"""Pydantic v2 models for every spec type accepted by the MCP tools."""

from typing import Annotated, Any, Literal, Optional, Union

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Distributions
# ---------------------------------------------------------------------------

class ExponDist(BaseModel):
    type: Literal["expon"]
    scale: float = Field(gt=0, description="Mean of the exponential distribution")


class UniformDist(BaseModel):
    type: Literal["uniform"]
    loc: float = Field(description="Lower bound")
    scale: float = Field(ge=0, description="Width (use 0 for a deterministic value equal to loc)")


class NormDist(BaseModel):
    type: Literal["norm"]
    loc: float = Field(description="Mean")
    scale: float = Field(gt=0, description="Standard deviation")


class TriangDist(BaseModel):
    type: Literal["triang"]
    c: float = Field(
        ge=0, le=1,
        description=(
            "Mode expressed as a fraction of the interval [loc, loc+scale]. "
            "c = (mode - loc) / scale. "
            "Example: triangle with min=2, mode=5, max=8 → loc=2, scale=6, c=0.5 (since (5-2)/6=0.5)."
        ),
    )
    loc: float = Field(description="Lower bound (minimum value)")
    scale: float = Field(gt=0, description="Width = max - min")


DistributionSpec = Annotated[
    Union[ExponDist, UniformDist, NormDist, TriangDist],
    Field(discriminator="type"),
]


# ---------------------------------------------------------------------------
# Gap 1 — Label-expression service time for MultiServer
# ---------------------------------------------------------------------------

class LabelExprSpec(BaseModel):
    """Service-time spec that reads the delay from an item label at runtime.

    The expression is evaluated as a Python expression with ``item`` in scope,
    so you can use ``item.get_label_value('PT1')`` or simple arithmetic on it.

    Examples:
        {"type": "label_expr", "expression": "item.get_label_value('PT1')"}
        {"type": "label_expr", "expression": "float(item.get_label_value('PT1')) * 60"}
    """
    type: Literal["label_expr"]
    expression: str = Field(
        min_length=1,
        description=(
            "Python expression evaluated per item. "
            "'item' is the Item instance currently being processed. "
            "Must return a non-negative number. "
            "Example: \"item.get_label_value('PT1')\""
        ),
    )


# ServiceTimeSpec accepts either a statistical distribution OR a label expression.
ServiceTimeSpec = Annotated[
    Union[ExponDist, UniformDist, NormDist, TriangDist, LabelExprSpec],
    Field(discriminator="type"),
]


# ---------------------------------------------------------------------------
# Elements
# ---------------------------------------------------------------------------

class InterArrivalSourceSpec(BaseModel):
    """Generates items on a random inter-arrival schedule.

    Gap 2: Optional ``item_type`` and ``labels`` fields attach a fixed type and
    label set to every item generated by this source (model_item pattern).
    """
    type: Literal["InterArrivalSource"]
    id: str = Field(min_length=1, pattern=r"^[a-zA-Z][a-zA-Z0-9_]*$",
                    description="Unique identifier used to reference this element in connections")
    name: str = Field(description="Human-readable display name")
    interarrival: DistributionSpec = Field(description="Distribution of time between consecutive arrivals")
    # Gap 2 additions
    item_type: Optional[str] = Field(
        default=None,
        description=(
            "Optional item type tag stamped on every generated item. "
            "Appears in per-type sink stats. Example: \"Type1\""
        ),
    )
    labels: Optional[dict[str, str]] = Field(
        default=None,
        description=(
            "Optional label dict copied onto every generated item. "
            "Use string values; the label_expr service-time strategy converts them to float. "
            "Example: {\"PT1\": \"10\", \"PT2\": \"5\"}"
        ),
    )


class ItemsQueueSpec(BaseModel):
    type: Literal["ItemsQueue"]
    id: str = Field(min_length=1, pattern=r"^[a-zA-Z][a-zA-Z0-9_]*$")
    name: str
    capacity: int = Field(
        gt=0,
        description=(
            "Maximum number of items the queue can hold. "
            "When full, the queue rejects new items: the upstream source blocks "
            "and does NOT schedule its next arrival until space becomes available. "
            "Items are never silently dropped — the source retries when notified."
        ),
    )


class MultiServerSpec(BaseModel):
    type: Literal["MultiServer"]
    id: str = Field(min_length=1, pattern=r"^[a-zA-Z][a-zA-Z0-9_]*$")
    name: str
    num_servers: int = Field(gt=0, description="Number of parallel processing slots")
    service_time: ServiceTimeSpec = Field(
        description=(
            "Service time per item. Either a statistical distribution spec "
            "(expon / uniform / norm / triang) or a label_expr spec that reads "
            "the delay from an item label at runtime."
        )
    )


class SinkSpec(BaseModel):
    type: Literal["Sink"]
    id: str = Field(min_length=1, pattern=r"^[a-zA-Z][a-zA-Z0-9_]*$")
    name: str


# ---------------------------------------------------------------------------
# Gap 3 — ScheduleSource: fixed job list released at specified times
# ---------------------------------------------------------------------------

class JobSpec(BaseModel):
    """One row in the ScheduleSource job table.

    Fields map directly to the ScheduleSource data_dict columns:
    Time, Name, Q (quantity), plus any number of label columns.

    Example:
        {"time": 0, "name": "J1", "qty": 1, "labels": {"PT1": "10", "PT2": "5"}}
    """
    time: float = Field(ge=0, description="Simulation time at which this job is released")
    name: str = Field(min_length=1, description="Job name; also used as the item type tag")
    qty: int = Field(default=1, gt=0, description="Number of identical items to release at this time")
    labels: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Arbitrary key-value label pairs attached to each generated item. "
            "Values can be numbers or strings. "
            "Example: {\"PT1\": 10, \"PT2\": 5}"
        ),
    )


class ScheduleSourceSpec(BaseModel):
    """Releases a predefined list of jobs at specified simulation times.

    Use this instead of InterArrivalSource when you have a finite, known set of
    jobs (e.g. 8 jobs all released at t=0 with individual processing times).

    The jobs list is converted to the data_dict format expected by PyFlow's
    ScheduleSource. Columns beyond Time/Name/Q become item labels accessible
    via item.get_label_value() — and therefore usable with label_expr service times.

    Example (8 jobs at t=0 with PT1/PT2 labels):
        {
          "type": "ScheduleSource",
          "id": "src",
          "name": "Source",
          "jobs": [
            {"time": 0, "name": "J1", "qty": 1, "labels": {"PT1": 10, "PT2": 5}},
            {"time": 0, "name": "J2", "qty": 1, "labels": {"PT1": 5,  "PT2": 15}},
            ...
          ]
        }
    """
    type: Literal["ScheduleSource"]
    id: str = Field(min_length=1, pattern=r"^[a-zA-Z][a-zA-Z0-9_]*$")
    name: str
    jobs: list[JobSpec] = Field(min_length=1, description="Ordered list of job release records")

    def to_data_dict(self) -> dict:
        """Convert to the data_dict format accepted by PyFlow's ScheduleSource."""
        # Collect the superset of label keys across all jobs (preserve insertion order).
        label_keys: list[str] = []
        for job in self.jobs:
            for k in job.labels:
                if k not in label_keys:
                    label_keys.append(k)

        data: dict[str, list] = {"Time": [], "Name": [], "Q": []}
        for k in label_keys:
            data[k] = []

        for job in self.jobs:
            data["Time"].append(job.time)
            data["Name"].append(job.name)
            data["Q"].append(job.qty)
            for k in label_keys:
                data[k].append(job.labels.get(k, None))

        return data


ElementSpec = Annotated[
    Union[InterArrivalSourceSpec, ItemsQueueSpec, MultiServerSpec, SinkSpec, ScheduleSourceSpec],
    Field(discriminator="type"),
]


# ---------------------------------------------------------------------------
# Connections
# ---------------------------------------------------------------------------

class ConnectionSpec(BaseModel):
    """A directed connection from one origin element to one or more destinations.

    All destinations sharing the same origin must be passed in a single spec so
    that PyFlow's connect() receives the full destination list at once — this
    is required for strategies like RoundRobin to work across the whole set.
    """

    origin: str = Field(description="Element id of the upstream element")
    destinations: list[str] = Field(min_length=1,
                                    description="One or more element ids to receive items from origin")
    strategy: Literal["FirstAvailable", "RoundRobin"] = Field(
        default="FirstAvailable",
        description="Output routing strategy applied to this connection",
    )
